language: python

# Generate resourcepacks as ZIP-archives
script: ./scripts/generate_resourcepacks.sh

before_deploy:
  - sha1sum ./target/resourcepack_v3.zip > ./target/resourcepack_v3.zip.sha1
  - sha1sum ./target/resourcepack_v4.zip > ./target/resourcepack_v4.zip.sha1

deploy:
  provider: releases
  api_key:
    secure: UeZaIkaZDTXi6HYjOa3kdXKCZR/IGTx5AA3w54ZAdRvtlMwnfWBlnNzKhTjB1oysepBfz3GQ7VLMi6bnnhraEHwC1k9DYzUUARAPqZjz9zNA6U+eK/LcpUe/SbzMhrRqYH4TXzIbYOipWKtv+EcZMrlqGpnCehV9PlZDB4eHDrhxrGt7Clw1XGzX5PISYhOa4pzwdLYV4uQpZna0B9x1HJpcs/OmLpYG1GZI/1832QBZSylpjH36ThotN2iSwMEFVFcP5HrVy1mAHkh+LtbNSTQpYU0GKTcPYtwMUBDSBTdjda0OZeocV25gzB2m9fGIF+guxChHLJBm0lZhmWtzwqZpCStOkftH/qFpBFH8a7+8QqCOkEc6t94GT3xdWHDc3qeyZzUqq2hB+VnFUYz6hGU666KPb1YZp0T9zIjxqwf3/8oQD8AF0YelKYkvBBToAjDZM4PKLkAjhsl01wgX3ZLL8RS3WCVDHzyH9GIon2Zj+b7WPnKZ8aZKIzgJ+LX+VqSSudYrWykQBexGSSZezVUqz9mNvu0YL2zu+bydumm9QLk6zd1Wt4J++085Yohy/RSzcmIlJFGZwDVFthBx3pJbdl6Wrn6f0SnJ77/LWeXYEi+6ctJW0motDUkHjHTFQ/yNMXGtmWY+FqXWo304qoDPtbiWVVCS2aYrNhcAEU4=
  file:
    - ./target/resourcepack_v3.zip
    - ./target/resourcepack_v3.zip.sha1
    - ./target/resourcepack_v4.zip
    - ./target/resourcepack_v4.zip.sha1
  on:
    tags: true
    branch: master
    repo: divine-craft/anarchy-resourcepack
  skip_cleanup: true
  cleanup: false
